// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: proto/ad_service.proto

package ad_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdType int32

const (
	AdType_UNKNOWN    AdType = 0
	AdType_FILM       AdType = 1
	AdType_WEB        AdType = 2
	AdType_WEB_BAR    AdType = 3
	AdType_WEB_CORNER AdType = 4
)

// Enum value maps for AdType.
var (
	AdType_name = map[int32]string{
		0: "UNKNOWN",
		1: "FILM",
		2: "WEB",
		3: "WEB_BAR",
		4: "WEB_CORNER",
	}
	AdType_value = map[string]int32{
		"UNKNOWN":    0,
		"FILM":       1,
		"WEB":        2,
		"WEB_BAR":    3,
		"WEB_CORNER": 4,
	}
)

func (x AdType) Enum() *AdType {
	p := new(AdType)
	*p = x
	return p
}

func (x AdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ad_service_proto_enumTypes[0].Descriptor()
}

func (AdType) Type() protoreflect.EnumType {
	return &file_proto_ad_service_proto_enumTypes[0]
}

func (x AdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdType.Descriptor instead.
func (AdType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ad_service_proto_rawDescGZIP(), []int{0}
}

type GetAdvertisementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AdType `protobuf:"varint,1,opt,name=type,proto3,enum=advertisement.AdType" json:"type,omitempty"`
}

func (x *GetAdvertisementRequest) Reset() {
	*x = GetAdvertisementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ad_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvertisementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertisementRequest) ProtoMessage() {}

func (x *GetAdvertisementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertisementRequest.ProtoReflect.Descriptor instead.
func (*GetAdvertisementRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAdvertisementRequest) GetType() AdType {
	if x != nil {
		return x.Type
	}
	return AdType_UNKNOWN
}

type GetAdvertisementReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	File   string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *GetAdvertisementReply) Reset() {
	*x = GetAdvertisementReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ad_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvertisementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertisementReply) ProtoMessage() {}

func (x *GetAdvertisementReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertisementReply.ProtoReflect.Descriptor instead.
func (*GetAdvertisementReply) Descriptor() ([]byte, []int) {
	return file_proto_ad_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAdvertisementReply) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetAdvertisementReply) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type SaveAdvertisementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       AdType                 `protobuf:"varint,1,opt,name=type,proto3,enum=advertisement.AdType" json:"type,omitempty"`
	Bucket     string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	File       string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	ExpireTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
}

func (x *SaveAdvertisementRequest) Reset() {
	*x = SaveAdvertisementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ad_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAdvertisementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAdvertisementRequest) ProtoMessage() {}

func (x *SaveAdvertisementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ad_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAdvertisementRequest.ProtoReflect.Descriptor instead.
func (*SaveAdvertisementRequest) Descriptor() ([]byte, []int) {
	return file_proto_ad_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveAdvertisementRequest) GetType() AdType {
	if x != nil {
		return x.Type
	}
	return AdType_UNKNOWN
}

func (x *SaveAdvertisementRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SaveAdvertisementRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SaveAdvertisementRequest) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

var File_proto_ad_service_proto protoreflect.FileDescriptor

var file_proto_ad_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x43, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0xae, 0x01, 0x0a, 0x18, 0x53, 0x61, 0x76, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x2a, 0x45, 0x0a, 0x06, 0x41, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x4d,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x57,
	0x45, 0x42, 0x5f, 0x42, 0x41, 0x52, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x45, 0x42, 0x5f,
	0x43, 0x4f, 0x52, 0x4e, 0x45, 0x52, 0x10, 0x04, 0x32, 0xb5, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x57, 0x0a, 0x05, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x12, 0x26, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x06, 0x53, 0x61, 0x76, 0x65, 0x41, 0x64, 0x12, 0x27, 0x2e,
	0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ad_service_proto_rawDescOnce sync.Once
	file_proto_ad_service_proto_rawDescData = file_proto_ad_service_proto_rawDesc
)

func file_proto_ad_service_proto_rawDescGZIP() []byte {
	file_proto_ad_service_proto_rawDescOnce.Do(func() {
		file_proto_ad_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ad_service_proto_rawDescData)
	})
	return file_proto_ad_service_proto_rawDescData
}

var file_proto_ad_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ad_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ad_service_proto_goTypes = []interface{}{
	(AdType)(0),                      // 0: advertisement.AdType
	(*GetAdvertisementRequest)(nil),  // 1: advertisement.GetAdvertisementRequest
	(*GetAdvertisementReply)(nil),    // 2: advertisement.GetAdvertisementReply
	(*SaveAdvertisementRequest)(nil), // 3: advertisement.SaveAdvertisementRequest
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 5: google.protobuf.Empty
}
var file_proto_ad_service_proto_depIdxs = []int32{
	0, // 0: advertisement.GetAdvertisementRequest.type:type_name -> advertisement.AdType
	0, // 1: advertisement.SaveAdvertisementRequest.type:type_name -> advertisement.AdType
	4, // 2: advertisement.SaveAdvertisementRequest.expire_time:type_name -> google.protobuf.Timestamp
	1, // 3: advertisement.Advertisement.GetAd:input_type -> advertisement.GetAdvertisementRequest
	3, // 4: advertisement.Advertisement.SaveAd:input_type -> advertisement.SaveAdvertisementRequest
	2, // 5: advertisement.Advertisement.GetAd:output_type -> advertisement.GetAdvertisementReply
	5, // 6: advertisement.Advertisement.SaveAd:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ad_service_proto_init() }
func file_proto_ad_service_proto_init() {
	if File_proto_ad_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ad_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdvertisementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ad_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdvertisementReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ad_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAdvertisementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ad_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ad_service_proto_goTypes,
		DependencyIndexes: file_proto_ad_service_proto_depIdxs,
		EnumInfos:         file_proto_ad_service_proto_enumTypes,
		MessageInfos:      file_proto_ad_service_proto_msgTypes,
	}.Build()
	File_proto_ad_service_proto = out.File
	file_proto_ad_service_proto_rawDesc = nil
	file_proto_ad_service_proto_goTypes = nil
	file_proto_ad_service_proto_depIdxs = nil
}
